# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}: {
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = ["nvme" "xhci_pci" "thunderbolt" "usb_storage" "sd_mod"];
  boot.initrd.kernelModules = [];
  boot.kernelModules = ["kvm-amd"];
  boot.extraModulePackages = [];

  # Added noatime option because of fstrim - SSD optimization
  fileSystems."/" = {
    device = "/dev/disk/by-uuid/fc4f99b9-6fbb-4c39-bfdb-f0c9ae9b582d";
    fsType = "btrfs";
    options = ["subvol=@" "noatime"];
  };

  boot.initrd.luks.devices."luks-8ed05793-6412-4df3-ab0b-5530d538522c".device = "/dev/disk/by-uuid/8ed05793-6412-4df3-ab0b-5530d538522c";

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/698E-300C";
    fsType = "vfat";
    options = ["fmask=0022" "dmask=0022"];
  };

  swapDevices = [
    {device = "/dev/disk/by-uuid/7bb230f8-fcbd-4cf6-bae6-c6eb6b8d6dea";}
  ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp1s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
